blank_issues_enabled: false
contact_links:
  - name: Report Issue about Blessing Skin plugins
    url: https://github.com/bs-community/blessing-skin-plugins/issues
    about: Please ask and answer questions there.
  - name: Report Issue about integrating with Flarum
    url: https://github.com/bs-community/flarum-oauth-client/issues
    about: Please ask and answer questions there.
  - name: 报告与 Blessing Skin 插件有关的问题
    url: https://github.com/bs-community/blessing-skin-plugins/issues
    about: 请在那里报告问题。
  - name: 报告与 Flarum 对接有关的问题
    url: https://github.com/bs-community/flarum-oauth-client/issues
    about: 请在那里报告问题。
